CREATE TABLE PRODUCTS (
  ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  NAME VARCHAR(120) NOT NULL,
  PRICE NUMERIC(12, 2),
  STOCK INTEGER,
  IMAGE VARCHAR(255)
);

INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Dipirona 500mg 20 comprimidos', 12.90, 48, 'https://example.com/images/dipirona.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Paracetamol 750mg 20 comprimidos', 15.50, 35, 'https://example.com/images/paracetamol.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Ibuprofeno 400mg 10 capsulas', 18.75, 22, 'https://example.com/images/ibuprofeno.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Loratadina 10mg 12 comprimidos', 21.30, 19, 'https://example.com/images/loratadina.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Omeprazol 20mg 28 capsulas', 26.40, 41, 'https://example.com/images/omeprazol.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Soro Fisiologico 500ml', 8.99, 60, 'https://example.com/images/soro.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Vitamina C 1g 10 comprimidos', 14.20, 27, 'https://example.com/images/vitamina-c.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Sabonete Antisseptico 90g', 6.80, 33, 'https://example.com/images/sabonete.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Protetor Solar FPS 50 120ml', 49.90, 16, 'https://example.com/images/protetor-solar.jpg');
INSERT INTO PRODUCTS (NAME, PRICE, STOCK, IMAGE) VALUES ('Termometro Digital', 29.90, 11, 'https://example.com/images/termometro.jpg');

COMMIT;
